export default {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_ERROR: 'SET_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',
  GET_ERROR: 'GET_ERROR',
  SET_MESSAGES: 'SET_MESSAGES',
  REMOVE_MESSAGES: 'REMOVE_MESSAGES',
  GET_MESSAGES: 'GET_MESSAGES',
}
